baseurl: ''
url: 'http://marlinfw.org'

version: '0.0.6'
environment: development

name: 'Marlin 3D Printer Firmware'
logo: '/assets/images/logo/marlin/small.png'
description: 'Printing the planet, one layer at a time.'

repository:
  main: 'https://github.com/MarlinFirmware/Marlin'
  dev: 'https://github.com/MarlinFirmware/MarlinDev'
  doc: 'https://github.com/MarlinFirmware/MarlinDocumentation'

analytics:
  id: 'UA-76230130-1'
  domain: 'marlinfw.org'

markdown: 'kramdown'
highlighter: 'rouge'
timezone: 'Europe/Lisbon'

collections:
  articles:
    output: true
  gcode:
    output: false

#include: [ '_pages' ]

exclude: [ '.gitignore', '_config.yml', 'CNAME', 'Gemfile', 'LICENSE', 'public', 'README.md', 'script', 'vendor' ]

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar

defaults:
  - # All types
    scope:
      path: '' # all files
    values:
      layout: 'default'
      author: 'MarlinFirmware'
      category: [ 'default' ]
      show:
        navbar: true
        footer: true
        breadcrumbs: false

  - # Meta type
    scope:
      path: 'meta'
    values:
      category: [ 'meta' ]
      show:
        breadcrumbs: false

  - # Article type settings
    scope:
      type: 'articles'
    values:
      layout: 'articles'
      show:
        breadcrumbs: true
