# Jekyll
safe:             'true'
exclude:          [ 'README.md', 'public', '_config.yml', 'LICENSE', '.gitignore' ]

# Site configuration
url:              'http://jbrazio.github.io/MarlinDocumentation'
title:            'Marlin Firmware'
subtitle:         'Documentation Project'
description:      'Learn how to get started using Marlin.'

# Assets location
css_url:          'assets/stylesheets'
js_url:           'assets/javascript'
img_url:          'assets/images'
assets_url:       'assets'

# Categories URL
articles_url :    'articles'

# Metadata
meta:
  version:        '0.0.1'
  author:         'Marlin Documentation Project'
  feedback_email: 'marlin-doc@this-is-not-a-valid-domain.org'

# Page defaults
defaults:
  -
    scope:
      path:               ''
      type:               'articles'

    values:
      navigation:
        show_title:       'true'
        show_navbar:      'true'
        show_footer:      'true'
        show_breadcrumbs: 'true'
        show_description: 'false'

      meta:
        hidden:           'false'
        categories:       [ 'default' ]
  -
    scope:
      path:               ''
      type:               'pages'

    values:
      navigation:
        show_title:       'true'
        show_navbar:      'true'
        show_footer:      'true'
        show_breadcrumbs: 'true'
        show_description: 'false'

      meta:
        hidden:           'false'
        categories:       [ 'default' ]
