# Jekyll
safe:             'true'
markdown:         'kramdown'
highlighter:      'rouge'
encoding:         'utf-8'

# Site configuration
url:              'http://jbrazio.github.io/MarlinDocumentation'
title:            'Marlin Firmware'
subtitle:         'Documentation Project'
description:      'Learn how to get started using Marlin.'

# jekyll serve parameters
port:             '4000'
host:             '127.0.0.1'

# Assets location
css_url:          'assets/stylesheets'
js_url:           'assets/javascript'
img_url:          'assets/images'
assets_url:       'assets'

# Categories
docs_url:         'articles/docs'
howto_url:        'articles/howto'
features_url:     'articles/features'

# Metadata
meta:
  version:        '0.0.1'
  author:         'Marlin Documentation Project'
  feedback_email: 'marlin-doc@this-is-not-a-valid-domain.org'

# Exclude non-site files
exclude: [ 'README.md', 'public', '_config.yml', 'LICENSE' ]

# --------------#
#    Defaults   #
# ------------- #
defaults:
  -
    scope:
      type:               'pages'
    values:
      navigation:
        show_title:       'true'
        show_navbar:      'true'
        show_footer:      'true'
        show_breadcrumbs: 'true'
        show_description: 'false'
      meta:
        hidden:           'false'
        categories: [ 'default' ]
