#
# Test Jekyll syntax for issues
#

name: Jekyll CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'MarlinFirmware/MarlinDocumentation'
    steps:
    - name: PR Checkout
      uses: actions/checkout@v2
    - name: Install Bundles
      run: bundle install
    - name: Test Build
      run: bundle exec jekyll build
