#
# jekyll-pub.yml
#
# Publish the Jekyll site whenever 'master' is pushed
#

name: Jekyll Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - name: Use Ruby >=2.4.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '>=2.4.4'
      - name: Check out 'master'
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Deploy Site
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
